# Generated by Django 4.0.1 on 2022-03-16 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningmodules',
            name='difficultyNumber',
        ),
        migrations.RemoveField(
            model_name='learningmodules',
            name='suggestedOrder',
        ),
    ]
