# Generated by Django 4.0.1 on 2022-02-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_quiz_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='name',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='topic',
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='title', max_length=120),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='required_score_to_pass',
            field=models.IntegerField(help_text='required score in %'),
        ),
    ]
