# Generated by Django 4.0.1 on 2022-03-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_remove_learningmodules_difficultynumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodules',
            name='difficultyNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learningmodules',
            name='suggestedOrder',
            field=models.IntegerField(default=0),
        ),
    ]
