# Generated by Django 4.0.1 on 2022-03-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_learningmodules_difficultynumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='assosModule',
            field=models.CharField(default='error404', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(default='title', max_length=100),
        ),
    ]
