# Generated by Django 4.0.1 on 2022-02-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_remove_question_text_remove_quiz_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='assosPage',
            field=models.CharField(default='Page Path', max_length=120),
        ),
    ]
