# Generated by Django 4.0.1 on 2022-02-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_quiz_assospage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='htmlPage',
            field=models.CharField(default='HTML Path', max_length=120),
        ),
    ]
