# Generated by Django 4.0.1 on 2022-02-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_quiz_htmlpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='learningmodules',
            name='text',
            field=models.ManyToManyField(to='learning.LearningText'),
        ),
    ]
