# Generated by Django 4.0.1 on 2022-02-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_learningtext_learningmodules_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningmodules',
            name='text',
        ),
        migrations.AddField(
            model_name='learningtext',
            name='module',
            field=models.ManyToManyField(to='learning.LearningModules'),
        ),
    ]
