# Generated by Django 4.0.1 on 2022-02-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_remove_learningmodules_text_learningtext_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodules',
            name='text',
            field=models.TextField(default='None'),
        ),
        migrations.DeleteModel(
            name='LearningText',
        ),
    ]
