# Generated by Django 4.0.1 on 2022-02-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_learningmodules_text_delete_learningtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodules',
            name='glossary',
            field=models.TextField(default='None'),
        ),
    ]
