# Generated by Django 4.0.1 on 2022-02-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_learningmodules_glossary'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodules',
            name='quizPath',
            field=models.CharField(default='quiz', max_length=100),
        ),
    ]
