# Generated by Django 4.0.1 on 2022-02-10 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_learningmodules_quizpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='module',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='learning.learningmodules'),
        ),
    ]
