# Generated by Django 4.0.1 on 2022-02-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_quiz_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodules',
            name='numberDocuments',
            field=models.IntegerField(default=0),
        ),
    ]
