# Generated by Django 4.0.1 on 2022-02-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='LearningModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(default='/home/default.jpg', max_length=100)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(max_length=15)),
                ('time', models.IntegerField()),
                ('learningPage', models.CharField(default='default', max_length=100)),
                ('tags', models.ManyToManyField(to='home.Tag')),
            ],
        ),
    ]
