# Generated by Django 4.0.1 on 2022-01-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningmodules',
            old_name='ttc',
            new_name='time',
        ),
        migrations.AddField(
            model_name='learningmodules',
            name='learningPage',
            field=models.CharField(default='learning.html', max_length=100),
        ),
    ]
