# Generated by Django 4.0.1 on 2022-01-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_ttc_learningmodules_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodules',
            name='image',
            field=models.CharField(default='/home/intro_to_cryptography.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='learningmodules',
            name='learningPage',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
