# Generated by Django 4.0.1 on 2022-02-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_learningmodules_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmodules',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'BEGINNER'), ('Intermediate', 'INTERMEDIATE'), ('Advanced', 'ADVANCED ')], default='BEGINNER', max_length=15),
        ),
    ]
