# Generated by Django 4.0.1 on 2022-02-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_learningmodules_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodules',
            name='pagePath',
            field=models.CharField(default='error404', max_length=100),
        ),
    ]
