# Generated by Django 4.0.1 on 2022-02-07 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_learningmodules_pagepath'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningModules',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
