# Generated by Django 4.0.1 on 2022-02-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_quiz_htmlpage'),
        ('users', '0003_profile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completedModules',
            field=models.ManyToManyField(to='learning.LearningModules'),
        ),
    ]
